# Top-level Runtime Settings
telemetry = false
logLevel = "warn"

[install]
minimumReleaseAge = 0
peer = true
linker = "isolated"

[run]
bun = true
shell = "bun"
noOrphans = true

[test]
preload = ["./src/core/__tests__/__mocks__/bunSetup.ts"]
smol = false
onlyFailures = true
isolate = true
randomize = true
