import { globSync } from 'glob';
import { defineConfig } from 'tsup';
import path from 'path';
import fs from 'fs/promises';

const generateCommandIndexPlugin = {
    name: 'generate-command-index',
    setup(build: any) {
        build.onLoad({ filter: /src[\\\/]core[\\\/]commands[\\\/]index\.ts$/ }, async () => {
            console.log('Generating command index for esbuild...');

            const SRC_DIR = path.resolve('src');
            const FEATURES_DIR = path.join(SRC_DIR, 'features');
            const EXCLUSIONS = new Set(['index.ts']);

            let featureDirs: string[] = [];
            try {
                const stats = await fs.stat(FEATURES_DIR);
                if (stats.isDirectory()) {
                    featureDirs = await fs.readdir(FEATURES_DIR);
                }
            } catch (error: any) {
                if (error.code !== 'ENOENT') {
                    console.warn(`Error reading features directory: ${error.message}`);
                }
            }

            const commandList: { varName: string; importPath: string }[] = [];

            if (featureDirs.length > 0) {
                await Promise.all(
                    featureDirs.map(async (feature) => {
                        const cmdDir = path.join(FEATURES_DIR, feature, 'commands');
                        try {
                            const entries = await fs.readdir(cmdDir);
                            const files = entries.filter((file) => file.endsWith('.ts') && !EXCLUSIONS.has(file));

                            for (const file of files) {
                                const baseName = path.basename(file, '.ts');
                                const safeFeature = feature.replaceAll(/[^a-zA-Z0-9]/g, '');
                                const safeFile = baseName.replaceAll(/[^a-zA-Z0-9]/g, '');
                                const varName = `cmd${safeFeature.charAt(0).toUpperCase() + safeFeature.slice(1)}${safeFile.charAt(0).toUpperCase() + safeFile.slice(1)}`;
                                const importPath = `@features/${feature}/commands/${baseName}.js`;

                                commandList.push({
                                    varName,
                                    importPath
                                });
                            }
                        } catch {
                            // Directory might not exist or be unreadable
                        }
                    })
                );
            }

            commandList.sort((a, b) => a.varName.localeCompare(b.varName));

            console.log(`Found ${commandList.length} command files.`);

            const imports = commandList.map((cmd) => `import ${cmd.varName} from '${cmd.importPath}';`).join('\n');
            const list = commandList.map((cmd) => cmd.varName).join(',\n        ');

            const content = `// Auto-generated by esbuild plugin
import { isDefined } from '@lib/guards.js';
import { commandManager } from './commandManager.js';

${imports}

export function loadCommands() {
    const commandModules = [
        ${list}
    ];

    for (const mod of commandModules) {
        if (isDefined(mod)) {
            if (Array.isArray(mod)) {
                for (const cmd of mod) commandManager.register(cmd);
            } else {
                commandManager.register(mod);
            }
        }
    }
}
`;

            return {
                contents: content,
                loader: 'ts',
                resolveDir: path.join(SRC_DIR, 'core', 'commands')
            };
        });
    }
};

// Find all config files
const configFiles = globSync('src/**/*Config{.ts,.default.ts}', {
    ignore: ['**/__tests__/**', '**/__mocks__/**', 'src/core/configManager*.ts', 'src/core/configurations.ts', 'src/core/configLoader.ts', 'src/features/anticheat/anticheatConfigLoader.ts']
});

configFiles.push('src/config.default.ts');

export default defineConfig({
    entry: ['src/core/main.ts', ...configFiles],
    outDir: 'build/behavior/scripts',
    format: ['esm'],
    target: 'es2022',
    bundle: true,
    splitting: false,
    clean: false, // We clean it with rimraf beforehand
    sourcemap: true,
    external: [
        '@minecraft/server',
        '@minecraft/server-ui',
        '@minecraft/server-gametest',
        '@minecraft/debug-utilities',
        '@minecraft/common',
        ...configFiles.map((file) => {
            let relativePath = file.replace('src/', './').replace('.ts', '.js');
            if (relativePath.endsWith('.default.js')) {
                relativePath = relativePath.replace('.default.js', '.js');
            }
            return relativePath;
        })
    ],
    esbuildOptions(options) {
        options.chunkNames = '[name]';
    },
    esbuildPlugins: [generateCommandIndexPlugin],
    outExtension({ format }) {
        return {
            js: '.js'
        };
    },
    async onSuccess() {
        // We need to rename the generated `.default.js` files to `.js`
        // However, if the user has defined a custom configuration file (e.g. config.ts),
        // we should not overwrite it with the default one.
        const { renameSync, existsSync, rmSync } = await import('fs');
        const { join } = await import('path');
        const { globSync } = await import('glob');

        const outDir = 'build/behavior/scripts';
        const generatedFiles = globSync('**/*.default.js', { cwd: outDir });

        for (const file of generatedFiles) {
            const oldPath = join(outDir, file);
            const newPath = oldPath.replace('.default.js', '.js');

            if (existsSync(newPath)) {
                // A custom config was compiled. Delete the default one instead of overwriting.
                rmSync(oldPath);
                if (existsSync(oldPath + '.map')) {
                    rmSync(oldPath + '.map');
                }
            } else {
                // Rename default to standard
                renameSync(oldPath, newPath);

                // Also rename maps if they exist
                if (existsSync(oldPath + '.map')) {
                    renameSync(oldPath + '.map', newPath + '.map');
                }
            }
        }
    }
});
