// Auto-generated by scripts/generate-command-index.js
import { isDefined } from '@lib/guards.js';
import { commandManager } from './commandManager.js';

import cmdAnticheatLogs from '@features/anticheat/commands/logs.js';
import cmdAnticheatNotify from '@features/anticheat/commands/notify.js';
import cmdAnticheatXraynotify from '@features/anticheat/commands/xraynotify.js';
import cmdAuctionHouseAh from '@features/auctionHouse/commands/ah.js';
import cmdDailyRewardsDaily from '@features/dailyRewards/commands/daily.js';
import cmdEconomyBalance from '@features/economy/commands/balance.js';
import cmdEconomyBounty from '@features/economy/commands/bounty.js';
import cmdEconomyPay from '@features/economy/commands/pay.js';
import cmdEconomySetbalance from '@features/economy/commands/setbalance.js';
import cmdEssentialsAnnouncement from '@features/essentials/commands/announcement.js';
import cmdEssentialsChattoconsole from '@features/essentials/commands/chattoconsole.js';
import cmdEssentialsClear from '@features/essentials/commands/clear.js';
import cmdEssentialsDebug from '@features/essentials/commands/debug.js';
import cmdEssentialsFixplayer from '@features/essentials/commands/fixplayer.js';
import cmdEssentialsFloatingtext from '@features/essentials/commands/floatingtext.js';
import cmdEssentialsGamemode from '@features/essentials/commands/gamemode.js';
import cmdEssentialsHelp from '@features/essentials/commands/help.js';
import cmdEssentialsLinks from '@features/essentials/commands/links.js';
import cmdEssentialsPanel from '@features/essentials/commands/panel.js';
import cmdEssentialsPvp from '@features/essentials/commands/pvp.js';
import cmdEssentialsRank from '@features/essentials/commands/rank.js';
import cmdEssentialsReload from '@features/essentials/commands/reload.js';
import cmdEssentialsRestart from '@features/essentials/commands/restart.js';
import cmdEssentialsRules from '@features/essentials/commands/rules.js';
import cmdEssentialsSave from '@features/essentials/commands/save.js';
import cmdEssentialsSidebar from '@features/essentials/commands/sidebar.js';
import cmdEssentialsSpawn from '@features/essentials/commands/spawn.js';
import cmdEssentialsStatus from '@features/essentials/commands/status.js';
import cmdEssentialsVersion from '@features/essentials/commands/version.js';
import cmdKitsKit from '@features/kits/commands/kit.js';
import cmdModerationBan from '@features/moderation/commands/ban.js';
import cmdModerationChatlog from '@features/moderation/commands/chatlog.js';
import cmdModerationClearchat from '@features/moderation/commands/clearchat.js';
import cmdModerationDimensionLock from '@features/moderation/commands/dimensionLock.js';
import cmdModerationFreeze from '@features/moderation/commands/freeze.js';
import cmdModerationInventory from '@features/moderation/commands/inventory.js';
import cmdModerationKick from '@features/moderation/commands/kick.js';
import cmdModerationMute from '@features/moderation/commands/mute.js';
import cmdModerationReport from '@features/moderation/commands/report.js';
import cmdModerationVanish from '@features/moderation/commands/vanish.js';
import cmdModerationWarn from '@features/moderation/commands/warn.js';
import cmdShopShop from '@features/shop/commands/shop.js';
import cmdSocialFriend from '@features/social/commands/friend.js';
import cmdTeamsTeam from '@features/teams/commands/team.js';
import cmdTeleportationBack from '@features/teleportation/commands/back.js';
import cmdTeleportationBackCommand from '@features/teleportation/commands/backCommand.js';
import cmdTeleportationDeathcoords from '@features/teleportation/commands/deathcoords.js';
import cmdTeleportationHome from '@features/teleportation/commands/home.js';
import cmdTeleportationRtp from '@features/teleportation/commands/rtp.js';
import cmdTeleportationTp from '@features/teleportation/commands/tp.js';
import cmdTeleportationTpa from '@features/teleportation/commands/tpa.js';
import cmdTeleportationWarp from '@features/teleportation/commands/warp.js';
import cmdVotingVote from '@features/voting/commands/vote.js';

export function loadCommands() {
    const commandModules = [
    cmdAnticheatLogs,
    cmdAnticheatNotify,
    cmdAnticheatXraynotify,
    cmdAuctionHouseAh,
    cmdDailyRewardsDaily,
    cmdEconomyBalance,
    cmdEconomyBounty,
    cmdEconomyPay,
    cmdEconomySetbalance,
    cmdEssentialsAnnouncement,
    cmdEssentialsChattoconsole,
    cmdEssentialsClear,
    cmdEssentialsDebug,
    cmdEssentialsFixplayer,
    cmdEssentialsFloatingtext,
    cmdEssentialsGamemode,
    cmdEssentialsHelp,
    cmdEssentialsLinks,
    cmdEssentialsPanel,
    cmdEssentialsPvp,
    cmdEssentialsRank,
    cmdEssentialsReload,
    cmdEssentialsRestart,
    cmdEssentialsRules,
    cmdEssentialsSave,
    cmdEssentialsSidebar,
    cmdEssentialsSpawn,
    cmdEssentialsStatus,
    cmdEssentialsVersion,
    cmdKitsKit,
    cmdModerationBan,
    cmdModerationChatlog,
    cmdModerationClearchat,
    cmdModerationDimensionLock,
    cmdModerationFreeze,
    cmdModerationInventory,
    cmdModerationKick,
    cmdModerationMute,
    cmdModerationReport,
    cmdModerationVanish,
    cmdModerationWarn,
    cmdShopShop,
    cmdSocialFriend,
    cmdTeamsTeam,
    cmdTeleportationBack,
    cmdTeleportationBackCommand,
    cmdTeleportationDeathcoords,
    cmdTeleportationHome,
    cmdTeleportationRtp,
    cmdTeleportationTp,
    cmdTeleportationTpa,
    cmdTeleportationWarp,
    cmdVotingVote
    ];

    for (const mod of commandModules) {
        if (isDefined(mod)) {
            if (Array.isArray(mod)) {
                for (const cmd of mod) commandManager.register(cmd);
            } else {
                commandManager.register(mod);
            }
        }
    }
}
