/**
 * A definitive and comprehensive database mapping Minecraft item IDs to their default texture paths and display names.
 * This is used to automatically assign icons and names to new items added to the shop.
 * Generated from the project's itemsConfig.js and supplemented with all other vanilla items.
 */
export const iconDB = {
    // From itemsConfig.js (Source of Truth)
    "minecraft:diamond": { icon: "textures/items/diamond", displayName: "Diamond" },
    "minecraft:emerald": { icon: "textures/items/emerald", displayName: "Emerald" },
    "minecraft:gold_ingot": { icon: "textures/items/gold_ingot", displayName: "Gold Ingot" },
    "minecraft:iron_ingot": { icon: "textures/items/iron_ingot", displayName: "Iron Ingot" },
    "minecraft:netherite_ingot": { icon: "textures/items/netherite_ingot", displayName: "Netherite Ingot" },
    "minecraft:netherite_scrap": { icon: "textures/items/netherite_scrap", displayName: "Netherite Scrap" },
    "minecraft:ancient_debris": { icon: "textures/blocks/ancient_debris_side", displayName: "Ancient Debris" },
    "minecraft:lapis_lazuli": { icon: "textures/blocks/lapis_ore", displayName: "Lapis Lazuli" },
    "minecraft:quartz": { icon: "textures/items/quartz", displayName: "Quartz" },
    "minecraft:totem_of_undying": { icon: "textures/items/totem", displayName: "Totem Of Undying" },
    "minecraft:nether_star": { icon: "textures/items/nether_star", displayName: "Nether Star" },
    "minecraft:shulker_shell": { icon: "textures/items/shulker_shell", displayName: "Shulker Shell" },
    "minecraft:elytra": { icon: "textures/items/elytra", displayName: "Elytra" },
    "minecraft:wither_skeleton_skull": { icon: "textures/items/spawn_eggs/spawn_egg_wither_skeleton", displayName: "Wither Skeleton Skull" },
    "minecraft:enchanted_golden_apple": { icon: "textures/items/apple_golden", displayName: "Enchanted Golden Apple" },
    "minecraft:diamond_sword": { icon: "textures/items/diamond_sword", displayName: "Diamond Sword" },
    "minecraft:diamond_pickaxe": { icon: "textures/items/diamond_pickaxe", displayName: "Diamond Pickaxe" },
    "minecraft:diamond_axe": { icon: "textures/items/diamond_axe", displayName: "Diamond Axe" },
    "minecraft:diamond_shovel": { icon: "textures/items/diamond_shovel", displayName: "Diamond Shovel" },
    "minecraft:diamond_hoe": { icon: "textures/items/diamond_hoe", displayName: "Diamond Hoe" },
    "minecraft:netherite_sword": { icon: "textures/items/netherite_sword", displayName: "Netherite Sword" },
    "minecraft:netherite_pickaxe": { icon: "textures/items/netherite_pickaxe", displayName: "Netherite Pickaxe" },
    "minecraft:diamond_helmet": { icon: "textures/items/diamond_helmet", displayName: "Diamond Helmet" },
    "minecraft:diamond_chestplate": { icon: "textures/items/diamond_chestplate", displayName: "Diamond Chestplate" },
    "minecraft:diamond_leggings": { icon: "textures/items/diamond_leggings", displayName: "Diamond Leggings" },
    "minecraft:diamond_boots": { icon: "textures/items/diamond_boots", displayName: "Diamond Boots" },
    "minecraft:netherite_helmet": { icon: "textures/items/netherite_helmet", displayName: "Netherite Helmet" },
    "minecraft:netherite_chestplate": { icon: "textures/items/netherite_chestplate", displayName: "Netherite Chestplate" },
    "minecraft:netherite_leggings": { icon: "textures/items/netherite_leggings", displayName: "Netherite Leggings" },
    "minecraft:netherite_boots": { icon: "textures/items/netherite_boots", displayName: "Netherite Boots" },
    "minecraft:oak_log": { icon: "textures/blocks/log_oak_top", displayName: "Oak Log" },
    "minecraft:spruce_log": { icon: "textures/blocks/log_spruce_top", displayName: "Spruce Log" },
    "minecraft:birch_log": { icon: "textures/blocks/log_birch_top", displayName: "Birch Log" },
    "minecraft:jungle_log": { icon: "textures/blocks/log_jungle_top", displayName: "Jungle Log" },
    "minecraft:acacia_log": { icon: "textures/blocks/log_acacia_top", displayName: "Acacia Log" },
    "minecraft:dark_oak_log": { icon: "textures/blocks/log_big_oak_top", displayName: "Dark Oak Log" },
    "minecraft:mangrove_log": { icon: "textures/blocks/mangrove_log_top", displayName: "Mangrove Log" },
    "minecraft:cherry_log": { icon: "textures/blocks/cherry_log_top", displayName: "Cherry Log" },
    "minecraft:crimson_stem": { icon: "textures/blocks/huge_fungus/crimson_log_top", displayName: "Crimson Stem" },
    "minecraft:warped_stem": { icon: "textures/blocks/huge_fungus/warped_stem_top", displayName: "Warped Stem" },
    "minecraft:stone": { icon: "textures/blocks/stone", displayName: "Stone" },
    "minecraft:cobblestone": { icon: "textures/blocks/cobblestone", displayName: "Cobblestone" },
    "minecraft:dirt": { icon: "textures/blocks/dirt", displayName: "Dirt" },
    "minecraft:sand": { icon: "textures/blocks/sand", displayName: "Sand" },
    "minecraft:gravel": { icon: "textures/blocks/gravel", displayName: "Gravel" },
    "minecraft:glass": { icon: "textures/blocks/glass", displayName: "Glass" },
    "minecraft:terracotta": { icon: "textures/blocks/hardened_clay", displayName: "Terracotta" },
    "minecraft:white_concrete": { icon: "textures/blocks/concrete_white", displayName: "White Concrete" },
    "minecraft:stone_bricks": { icon: "textures/blocks/stonebrick", displayName: "Stone Bricks" },
    "minecraft:obsidian": { icon: "textures/blocks/obsidian", displayName: "Obsidian" },
    "minecraft:glowstone": { icon: "textures/blocks/glowstone", displayName: "Glowstone" },
    "minecraft:netherrack": { icon: "textures/blocks/netherrack", displayName: "Netherrack" },
    "minecraft:end_stone": { icon: "textures/blocks/end_stone", displayName: "End Stone" },
    "minecraft:purpur_block": { icon: "textures/blocks/purpur_block", displayName: "Purpur Block" },
    "minecraft:cooked_beef": { icon: "textures/items/beef_cooked", displayName: "Steak" },
    "minecraft:cooked_porkchop": { icon: "textures/items/porkchop_cooked", displayName: "Cooked Porkchop" },
    "minecraft:bread": { icon: "textures/items/bread", displayName: "Bread" },
    "minecraft:golden_carrot": { icon: "textures/items/carrot_golden", displayName: "Golden Carrot" },
    "minecraft:cooked_salmon": { icon: "textures/items/fish_salmon_cooked", displayName: "Cooked Salmon" },
    "minecraft:cooked_cod": { icon: "textures/items/fish_cooked", displayName: "Cooked Cod" },
    "minecraft:chorus_fruit": { icon: "textures/items/chorus_fruit", displayName: "Chorus Fruit" },
    "minecraft:wheat": { icon: "textures/items/wheat", displayName: "Wheat" },
    "minecraft:carrot": { icon: "textures/items/carrot", displayName: "Carrot" },
    "minecraft:potato": { icon: "textures/items/potato", displayName: "Potato" },
    "minecraft:melon_slice": { icon: "textures/items/melon", displayName: "Melon Slice" },
    "minecraft:pumpkin": { icon: "textures/blocks/pumpkin_face_off", displayName: "Pumpkin" },
    "minecraft:sugar_cane": { icon: "textures/items/reeds", displayName: "Sugar Cane" },
    "minecraft:nether_wart": { icon: "textures/items/nether_wart", displayName: "Nether Wart" },
    "minecraft:enchanted_book": { icon: "textures/items/book_enchanted", displayName: "Enchanted Book" },
    "exe:panel": { icon: "textures/items/breeze_rod", displayName: "§l§bPanel§r" },
    "minecraft:apple": { icon: "textures/items/apple", displayName: "Apple" },
    "minecraft:arrow": { icon: "textures/items/arrow", displayName: "Arrow" },
    "minecraft:beef": { icon: "textures/items/beef_raw", displayName: "Raw Beef" },
    "minecraft:blaze_powder": { icon: "textures/items/blaze_powder", displayName: "Blaze Powder" },
    "minecraft:blaze_rod": { icon: "textures/items/blaze_rod", displayName: "Blaze Rod" },
    "minecraft:bone": { icon: "textures/items/bone", displayName: "Bone" },
    "minecraft:book": { icon: "textures/items/book_normal", displayName: "Book" },
    "minecraft:writable_book": { icon: "textures/items/book_writable", displayName: "Book and Quill" },
    "minecraft:written_book": { icon: "textures/items/book_written", displayName: "Written Book" },
    "minecraft:bowl": { icon: "textures/items/bowl", displayName: "Bowl" },
    "minecraft:bow": { icon: "textures/items/bow_standby", displayName: "Bow" },
    "minecraft:brewing_stand": { icon: "textures/items/brewing_stand", displayName: "Brewing Stand" },
    "minecraft:brick": { icon: "textures/items/brick", displayName: "Brick" },
    "minecraft:bucket": { icon: "textures/items/bucket_empty", displayName: "Bucket" },
    "minecraft:cake": { icon: "textures/items/cake", displayName: "Cake" },
    "minecraft:campfire": { icon: "textures/items/campfire", displayName: "Campfire" },
    "minecraft:carrot_on_a_stick": { icon: "textures/items/carrot_on_a_stick", displayName: "Carrot on a Stick" },
    "minecraft:beetroot": { icon: "textures/items/beetroot", displayName: "Beetroot" },
    "minecraft:cauldron": { icon: "textures/items/cauldron", displayName: "Cauldron" },
    "minecraft:charcoal": { icon: "textures/items/charcoal", displayName: "Charcoal" },
    "minecraft:chicken": { icon: "textures/items/chicken_raw", displayName: "Raw Chicken" },
    "minecraft:popped_chorus_fruit": { icon: "textures/items/chorus_fruit_popped", displayName: "Popped Chorus Fruit" },
    "minecraft:mutton": { icon: "textures/items/mutton_raw", displayName: "Raw Mutton" },
    "minecraft:clay_ball": { icon: "textures/items/clay_ball", displayName: "Clay Ball" },
    "minecraft:coal": { icon: "textures/items/coal", displayName: "Coal" },
    "minecraft:comparator": { icon: "textures/items/comparator", displayName: "Redstone Comparator" },
    "minecraft:cookie": { icon: "textures/items/cookie", displayName: "Cookie" },
    "minecraft:crossbow": { icon: "textures/items/crossbow_standby", displayName: "Crossbow" },
    "minecraft:diamond_horse_armor": { icon: "textures/items/diamond_horse_armor", displayName: "Diamond Horse Armor" },
    "minecraft:iron_door": { icon: "textures/items/door_iron", displayName: "Iron Door" },
    "minecraft:oak_door": { icon: "textures/items/door_wood", displayName: "Oak Door" },
    "minecraft:spruce_door": { icon: "textures/items/door_spruce", displayName: "Spruce Door" },
    "minecraft:birch_door": { icon: "textures/items/door_birch", displayName: "Birch Door" },
    "minecraft:jungle_door": { icon: "textures/items/door_jungle", displayName: "Jungle Door" },
    "minecraft:acacia_door": { icon: "textures/items/door_acacia", displayName: "Acacia Door" },
    "minecraft:dark_oak_door": { icon: "textures/items/door_dark_oak", displayName: "Dark Oak Door" },
    "minecraft:dragon_breath": { icon: "textures/items/dragons_breath", displayName: "Dragon's Breath" },
    "minecraft:dried_kelp": { icon: "textures/items/dried_kelp", displayName: "Dried Kelp" },
    "minecraft:egg": { icon: "textures/items/egg", displayName: "Egg" },
    "minecraft:ender_eye": { icon: "textures/items/ender_eye", displayName: "Eye of Ender" },
    "minecraft:ender_pearl": { icon: "textures/items/ender_pearl", displayName: "Ender Pearl" },
    "minecraft:end_crystal": { icon: "textures/items/end_crystal", displayName: "End Crystal" },
    "minecraft:experience_bottle": { icon: "textures/items/experience_bottle", displayName: "Bottle o' Enchanting" },
    "minecraft:feather": { icon: "textures/items/feather", displayName: "Feather" },
    "minecraft:fire_charge": { icon: "textures/items/fireball", displayName: "Fire Charge" },
    "minecraft:firework_rocket": { icon: "textures/items/fireworks", displayName: "Firework Rocket" },
    "minecraft:firework_star": { icon: "textures/items/fireworks_charge", displayName: "Firework Star" },
    "minecraft:fishing_rod": { icon: "textures/items/fishing_rod_uncast", displayName: "Fishing Rod" },
    "minecraft:cod": { icon: "textures/items/fish_raw", displayName: "Raw Cod" },
    "minecraft:salmon": { icon: "textures/items/fish_salmon_raw", displayName: "Raw Salmon" },
    "minecraft:tropical_fish": { icon: "textures/items/fish_clownfish_raw", displayName: "Tropical Fish" },
    "minecraft:pufferfish": { icon: "textures/items/fish_pufferfish_raw", displayName: "Pufferfish" },
    "minecraft:flint_and_steel": { icon: "textures/items/flint_and_steel", displayName: "Flint and Steel" },
    "minecraft:flower_pot": { icon: "textures/items/flower_pot", displayName: "Flower Pot" },
    "minecraft:ghast_tear": { icon: "textures/items/ghast_tear", displayName: "Ghast Tear" },
    "minecraft:glowstone_dust": { icon: "textures/items/glowstone_dust", displayName: "Glowstone Dust" },
    "minecraft:gold_horse_armor": { icon: "textures/items/gold_horse_armor", displayName: "Gold Horse Armor" },
    "minecraft:gold_nugget": { icon: "textures/items/gold_nugget", displayName: "Gold Nugget" },
    "minecraft:iron_nugget": { icon: "textures/items/iron_nugget", displayName: "Iron Nugget" },
    "minecraft:gunpowder": { icon: "textures/items/gunpowder", displayName: "Gunpowder" },
    "minecraft:hopper": { icon: "textures/items/hopper", displayName: "Hopper" },
    "minecraft:iron_horse_armor": { icon: "textures/items/iron_horse_armor", displayName: "Iron Horse Armor" },
    "minecraft:item_frame": { icon: "textures/items/item_frame", displayName: "Item Frame" },
    "minecraft:kelp": { icon: "textures/items/kelp", displayName: "Kelp" },
    "minecraft:lead": { icon: "textures/items/lead", displayName: "Lead" },
    "minecraft:leather": { icon: "textures/items/leather", displayName: "Leather" },
    "minecraft:leather_horse_armor": { icon: "textures/items/leather_horse_armor", displayName: "Leather Horse Armor" },
    "minecraft:magma_cream": { icon: "textures/items/magma_cream", displayName: "Magma Cream" },
    "minecraft:map": { icon: "textures/items/map_empty", displayName: "Empty Map" },
    "minecraft:filled_map": { icon: "textures/items/map_filled", displayName: "Map" },
    "minecraft:glistering_melon_slice": { icon: "textures/items/melon_speckled", displayName: "Glistering Melon Slice" },
    "minecraft:chest_minecart": { icon: "textures/items/minecart_chest", displayName: "Minecart with Chest" },
    "minecraft:command_block_minecart": { icon: "textures/items/minecart_command_block", displayName: "Minecart with Command Block" },
    "minecraft:furnace_minecart": { icon: "textures/items/minecart_furnace", displayName: "Minecart with Furnace" },
    "minecraft:hopper_minecart": { icon: "textures/items/minecart_hopper", displayName: "Minecart with Hopper" },
    "minecraft:minecart": { icon: "textures/items/minecart_normal", displayName: "Minecart" },
    "minecraft:tnt_minecart": { icon: "textures/items/minecart_tnt", displayName: "Minecart with TNT" },
    "minecraft:mushroom_stew": { icon: "textures/items/mushroom_stew", displayName: "Mushroom Stew" },
    "minecraft:beetroot_soup": { icon: "textures/items/beetroot_soup", displayName: "Beetroot Soup" },
    "minecraft:name_tag": { icon: "textures/items/name_tag", displayName: "Name Tag" },
    "minecraft:nautilus_shell": { icon: "textures/items/nautilus", displayName: "Nautilus Shell" },
    "minecraft:heart_of_the_sea": { icon: "textures/items/heartofthesea_closed", displayName: "Heart of the Sea" },
    "minecraft:nether_brick": { icon: "textures/items/netherbrick", displayName: "Nether Brick" },
    "minecraft:painting": { icon: "textures/items/painting", displayName: "Painting" },
    "minecraft:paper": { icon: "textures/items/paper", displayName: "Paper" },
    "minecraft:phantom_membrane": { icon: "textures/items/phantom_membrane", displayName: "Phantom Membrane" },
    "minecraft:porkchop": { icon: "textures/items/porkchop_raw", displayName: "Raw Porkchop" },
    "minecraft:baked_potato": { icon: "textures/items/potato_baked", displayName: "Baked Potato" },
    "minecraft:poisonous_potato": { icon: "textures/items/potato_poisonous", displayName: "Poisonous Potato" },
    "minecraft:glass_bottle": { icon: "textures/items/potion_bottle_empty", displayName: "Glass Bottle" },
    "minecraft:potion": { icon: "textures/items/potion_bottle_drinkable", displayName: "Potion" },
    "minecraft:splash_potion": { icon: "textures/items/potion_bottle_splash", displayName: "Splash Potion" },
    "minecraft:lingering_potion": { icon: "textures/items/potion_bottle_lingering", displayName: "Lingering Potion" },
    "minecraft:pumpkin_pie": { icon: "textures/items/pumpkin_pie", displayName: "Pumpkin Pie" },
    "minecraft:pumpkin_seeds": { icon: "textures/items/seeds_pumpkin", displayName: "Pumpkin Seeds" },
    "minecraft:prismarine_crystals": { icon: "textures/items/prismarine_crystals", displayName: "Prismarine Crystals" },
    "minecraft:prismarine_shard": { icon: "textures/items/prismarine_shard", displayName: "Prismarine Shard" },
    "minecraft:music_disc_11": { icon: "textures/items/record_11", displayName: "Music Disc (11)" },
    "minecraft:music_disc_13": { icon: "textures/items/record_13", displayName: "Music Disc (13)" },
    "minecraft:music_disc_blocks": { icon: "textures/items/record_blocks", displayName: "Music Disc (blocks)" },
    "minecraft:music_disc_cat": { icon: "textures/items/record_cat", displayName: "Music Disc (cat)" },
    "minecraft:music_disc_chirp": { icon: "textures/items/record_chirp", displayName: "Music Disc (chirp)" },
    "minecraft:music_disc_far": { icon: "textures/items/record_far", displayName: "Music Disc (far)" },
    "minecraft:music_disc_mall": { icon: "textures/items/record_mall", displayName: "Music Disc (mall)" },
    "minecraft:music_disc_mellohi": { icon: "textures/items/record_mellohi", displayName: "Music Disc (mellohi)" },
    "minecraft:music_disc_stal": { icon: "textures/items/record_stal", displayName: "Music Disc (stal)" },
    "minecraft:music_disc_strad": { icon: "textures/items/record_strad", displayName: "Music Disc (strad)" },
    "minecraft:music_disc_wait": { icon: "textures/items/record_wait", displayName: "Music Disc (wait)" },
    "minecraft:music_disc_ward": { icon: "textures/items/record_ward", displayName: "Music Disc (ward)" },
    "minecraft:music_disc_pigstep": { icon: "textures/items/record_pigstep", displayName: "Music Disc (Pigstep)" },
    "minecraft:music_disc_otherside": { icon: "textures/items/record_otherside", displayName: "Music Disc (otherside)" },
    "minecraft:music_disc_5": { icon: "textures/items/record_5", displayName: "Music Disc (5)" },
    "minecraft:music_disc_relic": { icon: "textures/items/music_disc_relic", displayName: "Music Disc (Relic)" },
    "minecraft:music_disc_creator": { icon: "textures/items/music_disc_creator", displayName: "Music Disc (Creator)" },
    "minecraft:music_disc_precipice": { icon: "textures/items/music_disc_precipice", displayName: "Music Disc (Precipice)" },
    "minecraft:redstone": { icon: "textures/items/redstone_dust", displayName: "Redstone Dust" },
    "minecraft:repeater": { icon: "textures/items/repeater", displayName: "Redstone Repeater" },
    "minecraft:rotten_flesh": { icon: "textures/items/rotten_flesh", displayName: "Rotten Flesh" },
    "minecraft:saddle": { icon: "textures/items/saddle", displayName: "Saddle" },
    "minecraft:melon_seeds": { icon: "textures/items/seeds_melon", displayName: "Melon Seeds" },
    "minecraft:wheat_seeds": { icon: "textures/items/seeds_wheat", displayName: "Wheat Seeds" },
    "minecraft:beetroot_seeds": { icon: "textures/items/seeds_beetroot", displayName: "Beetroot Seeds" },
    "minecraft:shears": { icon: "textures/items/shears", displayName: "Shears" },
    "minecraft:oak_sign": { icon: "textures/items/sign", displayName: "Oak Sign" },
    "minecraft:acacia_sign": { icon: "textures/items/sign_acacia", displayName: "Acacia Sign" },
    "minecraft:birch_sign": { icon: "textures/items/sign_birch", displayName: "Birch Sign" },
    "minecraft:dark_oak_sign": { icon: "textures/items/sign_darkoak", displayName: "Dark Oak Sign" },
    "minecraft:jungle_sign": { icon: "textures/items/sign_jungle", displayName: "Jungle Sign" },
    "minecraft:spruce_sign": { icon: "textures/items/sign_spruce", displayName: "Spruce Sign" },
    "minecraft:crimson_sign": { icon: "textures/items/sign_crimson", displayName: "Crimson Sign" },
    "minecraft:warped_sign": { icon: "textures/items/sign_warped", displayName: "Warped Sign" },
    "minecraft:mangrove_sign": { icon: "textures/items/mangrove_sign", displayName: "Mangrove Sign" },
    "minecraft:bamboo_sign": { icon: "textures/items/bamboo_sign", displayName: "Bamboo Sign" },
    "minecraft:cherry_sign": { icon: "textures/items/cherry_sign", displayName: "Cherry Sign" },
    "minecraft:oak_hanging_sign": { icon: "textures/items/oak_hanging_sign", displayName: "Oak Hanging Sign" },
    "minecraft:spruce_hanging_sign": { icon: "textures/items/spruce_hanging_sign", displayName: "Spruce Hanging Sign" },
    "minecraft:birch_hanging_sign": { icon: "textures/items/birch_hanging_sign", displayName: "Birch Hanging Sign" },
    "minecraft:jungle_hanging_sign": { icon: "textures/items/jungle_hanging_sign", displayName: "Jungle Hanging Sign" },
    "minecraft:acacia_hanging_sign": { icon: "textures/items/acacia_hanging_sign", displayName: "Acacia Hanging Sign" },
    "minecraft:dark_oak_hanging_sign": { icon: "textures/items/dark_oak_hanging_sign", displayName: "Dark Oak Hanging Sign" },
    "minecraft:crimson_hanging_sign": { icon: "textures/items/crimson_hanging_sign", displayName: "Crimson Hanging Sign" },
    "minecraft:warped_hanging_sign": { icon: "textures/items/warped_hanging_sign", displayName: "Warped Hanging Sign" },
    "minecraft:mangrove_hanging_sign": { icon: "textures/items/mangrove_hanging_sign", displayName: "Mangrove Hanging Sign" },
    "minecraft:bamboo_hanging_sign": { icon: "textures/items/bamboo_hanging_sign", displayName: "Bamboo Hanging Sign" },
    "minecraft:cherry_hanging_sign": { icon: "textures/items/cherry_hanging_sign", displayName: "Cherry Hanging Sign" },
    "minecraft:slime_ball": { icon: "textures/items/slimeball", displayName: "Slimeball" },
    "minecraft:snowball": { icon: "textures/items/snowball", displayName: "Snowball" },
    "minecraft:spider_eye": { icon: "textures/items/spider_eye", displayName: "Spider Eye" },
    "minecraft:fermented_spider_eye": { icon: "textures/items/spider_eye_fermented", displayName: "Fermented Spider Eye" },
    "minecraft:stick": { icon: "textures/items/stick", displayName: "Stick" },
    "minecraft:string": { icon: "textures/items/string", displayName: "String" },
    "minecraft:sugar": { icon: "textures/items/sugar", displayName: "Sugar" },
    "minecraft:suspicious_stew": { icon: "textures/items/suspicious_stew", displayName: "Suspicious Stew" },
    "minecraft:clock": { icon: "textures/items/clock_item", displayName: "Clock" },
    "minecraft:compass": { icon: "textures/items/compass_item", displayName: "Compass" },
    "minecraft:rabbit_foot": { icon: "textures/items/rabbit_foot", displayName: "Rabbit's Foot" },
    "minecraft:rabbit_hide": { icon: "textures/items/rabbit_hide", displayName: "Rabbit Hide" },
    "minecraft:rabbit_stew": { icon: "textures/items/rabbit_stew", displayName: "Rabbit Stew" },
    "minecraft:lever": { icon: "textures/items/lever", displayName: "Lever" },
    "minecraft:camera": { icon: "textures/items/camera", displayName: "Camera" },
    "minecraft:scute": { icon: "textures/items/turtle_shell_piece", displayName: "Scute" },
    "minecraft:turtle_helmet": { icon: "textures/items/turtle_helmet", displayName: "Turtle Shell" },
    "minecraft:armor_stand": { icon: "textures/items/armor_stand", displayName: "Armor Stand" },
    "minecraft:sweet_berries": { icon: "textures/items/sweet_berries", displayName: "Sweet Berries" },
    "minecraft:banner_pattern": { icon: "textures/items/banner_pattern", displayName: "Banner Pattern" },
    "minecraft:honeycomb": { icon: "textures/items/honeycomb", displayName: "Honeycomb" },
    "minecraft:honey_bottle": { icon: "textures/items/honey_bottle", displayName: "Honey Bottle" },
    "minecraft:lodestone_compass": { icon: "textures/items/lodestonecompass_item", displayName: "Lodestone Compass" },
    "minecraft:warped_fungus_on_a_stick": { icon: "textures/items/warped_fungus_on_a_stick", displayName: "Warped Fungus on a Stick" },
    "minecraft:chain": { icon: "textures/items/chain", displayName: "Chain" },
    "minecraft:soul_campfire": { icon: "textures/items/soul_campfire", displayName: "Soul Campfire" },
    "minecraft:nether_sprouts": { icon: "textures/items/nether_sprouts", displayName: "Nether Sprouts" },
    "minecraft:hanging_roots": { icon: "textures/items/hanging_roots", displayName: "Hanging Roots" },
    "minecraft:glow_berries": { icon: "textures/items/glow_berries", displayName: "Glow Berries" },
    "minecraft:amethyst_shard": { icon: "textures/items/amethyst_shard", displayName: "Amethyst Shard" },
    "minecraft:spyglass": { icon: "textures/items/spyglass", displayName: "Spyglass" },
    "minecraft:copper_ingot": { icon: "textures/items/copper_ingot", displayName: "Copper Ingot" },
    "minecraft:raw_copper": { icon: "textures/items/raw_copper", displayName: "Raw Copper" },
    "minecraft:raw_iron": { icon: "textures/items/raw_iron", displayName: "Raw Iron" },
    "minecraft:raw_gold": { icon: "textures/items/raw_gold", displayName: "Raw Gold" },
    "minecraft:glow_item_frame": { icon: "textures/items/glow_item_frame", displayName: "Glow Item Frame" },
    "minecraft:recovery_compass": { icon: "textures/items/recovery_compass_item", displayName: "Recovery Compass" },
    "minecraft:echo_shard": { icon: "textures/items/echo_shard", displayName: "Echo Shard" },
    "minecraft:goat_horn": { icon: "textures/items/goat_horn", displayName: "Goat Horn" },
    "minecraft:disc_fragment_5": { icon: "textures/items/disc_fragment_5", displayName: "Disc Fragment (5)" },
    "minecraft:pitcher_pod": { icon: "textures/items/pitcher_pod", displayName: "Pitcher Pod" },
    "minecraft:torchflower_seeds": { icon: "textures/items/torchflower_seeds", displayName: "Torchflower Seeds" },
    "minecraft:bamboo_door": { icon: "textures/items/bamboo_door", displayName: "Bamboo Door" },
    "minecraft:cherry_door": { icon: "textures/items/cherry_door", displayName: "Cherry Door" },
    "minecraft:angler_pottery_sherd": { icon: "textures/items/angler_pottery_sherd", displayName: "Angler Pottery Sherd" },
    "minecraft:archer_pottery_sherd": { icon: "textures/items/archer_pottery_sherd", displayName: "Archer Pottery Sherd" },
    "minecraft:arms_up_pottery_sherd": { icon: "textures/items/arms_up_pottery_sherd", displayName: "Arms Up Pottery Sherd" },
    "minecraft:blade_pottery_sherd": { icon: "textures/items/blade_pottery_sherd", displayName: "Blade Pottery Sherd" },
    "minecraft:brewer_pottery_sherd": { icon: "textures/items/brewer_pottery_sherd", displayName: "Brewer Pottery Sherd" },
    "minecraft:burn_pottery_sherd": { icon: "textures/items/burn_pottery_sherd", displayName: "Burn Pottery Sherd" },
    "minecraft:danger_pottery_sherd": { icon: "textures/items/danger_pottery_sherd", displayName: "Danger Pottery Sherd" },
    "minecraft:explorer_pottery_sherd": { icon: "textures/items/explorer_pottery_sherd", displayName: "Explorer Pottery Sherd" },
    "minecraft:friend_pottery_sherd": { icon: "textures/items/friend_pottery_sherd", displayName: "Friend Pottery Sherd" },
    "minecraft:heart_pottery_sherd": { icon: "textures/items/heart_pottery_sherd", displayName: "Heart Pottery Sherd" },
    "minecraft:heartbreak_pottery_sherd": { icon: "textures/items/heartbreak_pottery_sherd", displayName: "Heartbreak Pottery Sherd" },
    "minecraft:howl_pottery_sherd": { icon: "textures/items/howl_pottery_sherd", displayName: "Howl Pottery Sherd" },
    "minecraft:miner_pottery_sherd": { icon: "textures/items/miner_pottery_sherd", displayName: "Miner Pottery Sherd" },
    "minecraft:mourner_pottery_sherd": { icon: "textures/items/mourner_pottery_sherd", displayName: "Mourner Pottery Sherd" },
    "minecraft:plenty_pottery_sherd": { icon: "textures/items/plenty_pottery_sherd", displayName: "Plenty Pottery Sherd" },
    "minecraft:prize_pottery_sherd": { icon: "textures/items/prize_pottery_sherd", displayName: "Prize Pottery Sherd" },
    "minecraft:sheaf_pottery_sherd": { icon: "textures/items/sheaf_pottery_sherd", displayName: "Sheaf Pottery Sherd" },
    "minecraft:shelter_pottery_sherd": { icon: "textures/items/shelter_pottery_sherd", displayName: "Shelter Pottery Sherd" },
    "minecraft:skull_pottery_sherd": { icon: "textures/items/skull_pottery_sherd", displayName: "Skull Pottery Sherd" },
    "minecraft:snort_pottery_sherd": { icon: "textures/items/snort_pottery_sherd", displayName: "Snort Pottery Sherd" },
    "minecraft:brush": { icon: "textures/items/brush", displayName: "Brush" },
    "minecraft:netherite_upgrade_smithing_template": { icon: "textures/items/netherite_upgrade_smithing_template", displayName: "Netherite Upgrade" },
    "minecraft:sentry_armor_trim_smithing_template": { icon: "textures/items/sentry_armor_trim_smithing_template", displayName: "Sentry Armor Trim" },
    "minecraft:dune_armor_trim_smithing_template": { icon: "textures/items/dune_armor_trim_smithing_template", displayName: "Dune Armor Trim" },
    "minecraft:coast_armor_trim_smithing_template": { icon: "textures/items/coast_armor_trim_smithing_template", displayName: "Coast Armor Trim" },
    "minecraft:wild_armor_trim_smithing_template": { icon: "textures/items/wild_armor_trim_smithing_template", displayName: "Wild Armor Trim" },
    "minecraft:ward_armor_trim_smithing_template": { icon: "textures/items/ward_armor_trim_smithing_template", displayName: "Ward Armor Trim" },
    "minecraft:eye_armor_trim_smithing_template": { icon: "textures/items/eye_armor_trim_smithing_template", displayName: "Eye Armor Trim" },
    "minecraft:vex_armor_trim_smithing_template": { icon: "textures/items/vex_armor_trim_smithing_template", displayName: "Vex Armor Trim" },
    "minecraft:tide_armor_trim_smithing_template": { icon: "textures/items/tide_armor_trim_smithing_template", displayName: "Tide Armor Trim" },
    "minecraft:snout_armor_trim_smithing_template": { icon: "textures/items/snout_armor_trim_smithing_template", displayName: "Snout Armor Trim" },
    "minecraft:rib_armor_trim_smithing_template": { icon: "textures/items/rib_armor_trim_smithing_template", displayName: "Rib Armor Trim" },
    "minecraft:spire_armor_trim_smithing_template": { icon: "textures/items/spire_armor_trim_smithing_template", displayName: "Spire Armor Trim" },
    "minecraft:silence_armor_trim_smithing_template": { icon: "textures/items/silence_armor_trim_smithing_template", displayName: "Silence Armor Trim" },
    "minecraft:wayfinder_armor_trim_smithing_template": { icon: "textures/items/wayfinder_armor_trim_smithing_template", displayName: "Wayfinder Armor Trim" },
    "minecraft:raiser_armor_trim_smithing_template": { icon: "textures/items/raiser_armor_trim_smithing_template", displayName: "Raiser Armor Trim" },
    "minecraft:shaper_armor_trim_smithing_template": { icon: "textures/items/shaper_armor_trim_smithing_template", displayName: "Shaper Armor Trim" },
    "minecraft:host_armor_trim_smithing_template": { icon: "textures/items/host_armor_trim_smithing_template", displayName: "Host Armor Trim" },
    "minecraft:armadillo_scute": { icon: "textures/items/armadillo_scute", displayName: "Armadillo Scute" },
    "minecraft:wolf_armor": { icon: "textures/items/wolf_armor", displayName: "Wolf Armor" },
    "minecraft:copper_door": { icon: "textures/items/copper_door", displayName: "Copper Door" },
    "minecraft:exposed_copper_door": { icon: "textures/items/exposed_copper_door", displayName: "Exposed Copper Door" },
    "minecraft:weathered_copper_door": { icon: "textures/items/weathered_copper_door", displayName: "Weathered Copper Door" },
    "minecraft:oxidized_copper_door": { icon: "textures/items/oxidized_copper_door", displayName: "Oxidized Copper Door" },
    "minecraft:trial_key": { icon: "textures/items/trial_key", displayName: "Trial Key" },
    "minecraft:ominous_trial_key": { icon: "textures/items/ominous_trial_key", displayName: "Ominous Trial Key" },
    "minecraft:wind_charge": { icon: "textures/items/wind_charge", displayName: "Wind Charge" },
    "minecraft:guster_pottery_sherd": { icon: "textures/items/guster_pottery_sherd", displayName: "Guster Pottery Sherd" },
    "minecraft:flow_pottery_sherd": { icon: "textures/items/flow_pottery_sherd", displayName: "Flow Pottery Sherd" },
    "minecraft:scrape_pottery_sherd": { icon: "textures/items/scrape_pottery_sherd", displayName: "Scrape Pottery Sherd" },
    "minecraft:flow_banner_pattern": { icon: "textures/items/flow_banner_pattern", displayName: "Flow Banner Pattern" },
    "minecraft:guster_banner_pattern": { icon: "textures/items/guster_banner_pattern", displayName: "Guster Banner Pattern" },
    "minecraft:creeper_banner_pattern": { icon: "textures/items/creeper_banner_pattern", displayName: "Creeper Banner Pattern" },
    "minecraft:skull_banner_pattern": { icon: "textures/items/skull_banner_pattern", displayName: "Skull Banner Pattern" },
    "minecraft:flower_banner_pattern": { icon: "textures/items/flower_banner_pattern", displayName: "Flower Banner Pattern" },
    "minecraft:mojang_banner_pattern": { icon: "textures/items/mojang_banner_pattern", displayName: "Mojang Banner Pattern" },
    "minecraft:globe_banner_pattern": { icon: "textures/items/globe_banner_pattern", displayName: "Globe Banner Pattern" },
    "minecraft:piglin_banner_pattern": { icon: "textures/items/piglin_banner_pattern", displayName: "Piglin Banner Pattern" },
    "minecraft:breeze_rod": { icon: "textures/items/breeze_rod", displayName: "Breeze Rod" },
    "minecraft:flow_armor_trim_smithing_template": { icon: "textures/items/flow_armor_trim_smithing_template", displayName: "Flow Armor Trim" },
    "minecraft:bolt_armor_trim_smithing_template": { icon: "textures/items/bolt_armor_trim_smithing_template", displayName: "Bolt Armor Trim" },
    "minecraft:ominous_bottle": { icon: "textures/items/ominous_bottle", displayName: "Ominous Bottle" },
    "minecraft:tipped_arrow": { icon: "textures/items/tipped_arrow", displayName: "Tipped Arrow" },

    // Spawn Eggs
    "minecraft:allay_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_allay", displayName: "Allay Spawn Egg" },
    "minecraft:axolotl_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_axolotl", displayName: "Axolotl Spawn Egg" },
    "minecraft:bat_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_bat", displayName: "Bat Spawn Egg" },
    "minecraft:bee_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_bee", displayName: "Bee Spawn Egg" },
    "minecraft:blaze_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_blaze", displayName: "Blaze Spawn Egg" },
    "minecraft:bogged_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_bogged", displayName: "Bogged Spawn Egg" },
    "minecraft:breeze_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_breeze", displayName: "Breeze Spawn Egg" },
    "minecraft:camel_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_camel", displayName: "Camel Spawn Egg" },
    "minecraft:cat_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_cat", displayName: "Cat Spawn Egg" },
    "minecraft:cave_spider_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_cave_spider", displayName: "Cave Spider Spawn Egg" },
    "minecraft:chicken_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_chicken", displayName: "Chicken Spawn Egg" },
    "minecraft:cod_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_cod", displayName: "Cod Spawn Egg" },
    "minecraft:cow_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_cow", displayName: "Cow Spawn Egg" },
    "minecraft:creeper_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_creeper", displayName: "Creeper Spawn Egg" },
    "minecraft:dolphin_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_dolphin", displayName: "Dolphin Spawn Egg" },
    "minecraft:donkey_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_donkey", displayName: "Donkey Spawn Egg" },
    "minecraft:drowned_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_drowned", displayName: "Drowned Spawn Egg" },
    "minecraft:elder_guardian_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_elder_guardian", displayName: "Elder Guardian Spawn Egg" },
    "minecraft:ender_dragon_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_ender_dragon", displayName: "Ender Dragon Spawn Egg" },
    "minecraft:enderman_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_enderman", displayName: "Enderman Spawn Egg" },
    "minecraft:endermite_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_endermite", displayName: "Endermite Spawn Egg" },
    "minecraft:evoker_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_evoker", displayName: "Evoker Spawn Egg" },
    "minecraft:fox_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_fox", displayName: "Fox Spawn Egg" },
    "minecraft:frog_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_frog", displayName: "Frog Spawn Egg" },
    "minecraft:ghast_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_ghast", displayName: "Ghast Spawn Egg" },
    "minecraft:glow_squid_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_glow_squid", displayName: "Glow Squid Spawn Egg" },
    "minecraft:goat_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_goat", displayName: "Goat Spawn Egg" },
    "minecraft:guardian_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_guardian", displayName: "Guardian Spawn Egg" },
    "minecraft:hoglin_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_hoglin", displayName: "Hoglin Spawn Egg" },
    "minecraft:horse_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_horse", displayName: "Horse Spawn Egg" },
    "minecraft:husk_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_husk", displayName: "Husk Spawn Egg" },
    "minecraft:iron_golem_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_iron_golem", displayName: "Iron Golem Spawn Egg" },
    "minecraft:llama_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_llama", displayName: "Llama Spawn Egg" },
    "minecraft:magma_cube_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_magma_cube", displayName: "Magma Cube Spawn Egg" },
    "minecraft:mooshroom_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_mooshroom", displayName: "Mooshroom Spawn Egg" },
    "minecraft:mule_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_mule", displayName: "Mule Spawn Egg" },
    "minecraft:ocelot_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_ocelot", displayName: "Ocelot Spawn Egg" },
    "minecraft:panda_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_panda", displayName: "Panda Spawn Egg" },
    "minecraft:parrot_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_parrot", displayName: "Parrot Spawn Egg" },
    "minecraft:phantom_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_phantom", displayName: "Phantom Spawn Egg" },
    "minecraft:pig_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_pig", displayName: "Pig Spawn Egg" },
    "minecraft:piglin_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_piglin", displayName: "Piglin Spawn Egg" },
    "minecraft:piglin_brute_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_piglin_brute", displayName: "Piglin Brute Spawn Egg" },
    "minecraft:pillager_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_pillager", displayName: "Pillager Spawn Egg" },
    "minecraft:polar_bear_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_polar_bear", displayName: "Polar Bear Spawn Egg" },
    "minecraft:pufferfish_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_pufferfish", displayName: "Pufferfish Spawn Egg" },
    "minecraft:rabbit_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_rabbit", displayName: "Rabbit Spawn Egg" },
    "minecraft:ravager_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_ravager", displayName: "Ravager Spawn Egg" },
    "minecraft:salmon_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_salmon", displayName: "Salmon Spawn Egg" },
    "minecraft:sheep_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_sheep", displayName: "Sheep Spawn Egg" },
    "minecraft:shulker_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_shulker", displayName: "Shulker Spawn Egg" },
    "minecraft:silverfish_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_silverfish", displayName: "Silverfish Spawn Egg" },
    "minecraft:skeleton_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_skeleton", displayName: "Skeleton Spawn Egg" },
    "minecraft:skeleton_horse_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_skeleton_horse", displayName: "Skeleton Horse Spawn Egg" },
    "minecraft:slime_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_slime", displayName: "Slime Spawn Egg" },
    "minecraft:sniffer_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_sniffer", displayName: "Sniffer Spawn Egg" },
    "minecraft:snow_golem_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_snow_golem", displayName: "Snow Golem Spawn Egg" },
    "minecraft:spider_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_spider", displayName: "Spider Spawn Egg" },
    "minecraft:squid_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_squid", displayName: "Squid Spawn Egg" },
    "minecraft:stray_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_stray", displayName: "Stray Spawn Egg" },
    "minecraft:strider_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_strider", displayName: "Strider Spawn Egg" },
    "minecraft:tadpole_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_tadpole", displayName: "Tadpole Spawn Egg" },
    "minecraft:trader_llama_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_trader_llama", displayName: "Trader Llama Spawn Egg" },
    "minecraft:tropical_fish_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_tropicalfish", displayName: "Tropical Fish Spawn Egg" },
    "minecraft:turtle_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_turtle", displayName: "Turtle Spawn Egg" },
    "minecraft:vex_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_vex", displayName: "Vex Spawn Egg" },
    "minecraft:villager_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_villager", displayName: "Villager Spawn Egg" },
    "minecraft:vindicator_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_vindicator", displayName: "Vindicator Spawn Egg" },
    "minecraft:warden_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_warden", displayName: "Warden Spawn Egg" },
    "minecraft:witch_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_witch", displayName: "Witch Spawn Egg" },
    "minecraft:wither_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_wither", displayName: "Wither Spawn Egg" },
    "minecraft:wither_skeleton_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_wither_skeleton", displayName: "Wither Skeleton Spawn Egg" },
    "minecraft:wolf_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_wolf", displayName: "Wolf Spawn Egg" },
    "minecraft:zoglin_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_zoglin", displayName: "Zoglin Spawn Egg" },
    "minecraft:zombie_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_zombie", displayName: "Zombie Spawn Egg" },
    "minecraft:zombie_horse_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_zombie_horse", displayName: "Zombie Horse Spawn Egg" },
    "minecraft:zombified_piglin_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_zombified_piglin", displayName: "Zombified Piglin Spawn Egg" },
    "minecraft:zombie_villager_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_zombie_villager", displayName: "Zombie Villager Spawn Egg" },
    "minecraft:armadillo_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_armadillo", displayName: "Armadillo Spawn Egg" }
};