/**
 * A comprehensive database mapping Minecraft item IDs to their default texture paths and display names.
 * This is used to automatically assign icons and names to new items added to the shop.
 * Generated from the project's itemsConfig.js and supplemented with other common items.
 */
export const iconDB = {
    "minecraft:diamond": { icon: "textures/items/diamond", displayName: "Diamond" },
    "minecraft:emerald": { icon: "textures/items/emerald", displayName: "Emerald" },
    "minecraft:gold_ingot": { icon: "textures/items/gold_ingot", displayName: "Gold Ingot" },
    "minecraft:iron_ingot": { icon: "textures/items/iron_ingot", displayName: "Iron Ingot" },
    "minecraft:netherite_ingot": { icon: "textures/items/netherite_ingot", displayName: "Netherite Ingot" },
    "minecraft:netherite_scrap": { icon: "textures/items/netherite_scrap", displayName: "Netherite Scrap" },
    "minecraft:ancient_debris": { icon: "textures/blocks/ancient_debris_side", displayName: "Ancient Debris" },
    "minecraft:lapis_lazuli": { icon: "textures/blocks/lapis_ore", displayName: "Lapis Lazuli" },
    "minecraft:quartz": { icon: "textures/items/quartz", displayName: "Quartz" },
    "minecraft:totem_of_undying": { icon: "textures/items/totem", displayName: "Totem Of Undying" },
    "minecraft:nether_star": { icon: "textures/items/nether_star", displayName: "Nether Star" },
    "minecraft:shulker_shell": { icon: "textures/items/shulker_shell", displayName: "Shulker Shell" },
    "minecraft:elytra": { icon: "textures/items/elytra", displayName: "Elytra" },
    "minecraft:wither_skeleton_skull": { icon: "textures/items/spawn_eggs/spawn_egg_wither_skeleton", displayName: "Wither Skeleton Skull" },
    "minecraft:enchanted_golden_apple": { icon: "textures/items/apple_golden", displayName: "Enchanted Golden Apple" },
    "minecraft:diamond_sword": { icon: "textures/items/diamond_sword", displayName: "Diamond Sword" },
    "minecraft:diamond_pickaxe": { icon: "textures/items/diamond_pickaxe", displayName: "Diamond Pickaxe" },
    "minecraft:diamond_axe": { icon: "textures/items/diamond_axe", displayName: "Diamond Axe" },
    "minecraft:diamond_shovel": { icon: "textures/items/diamond_shovel", displayName: "Diamond Shovel" },
    "minecraft:diamond_hoe": { icon: "textures/items/diamond_hoe", displayName: "Diamond Hoe" },
    "minecraft:netherite_sword": { icon: "textures/items/netherite_sword", displayName: "Netherite Sword" },
    "minecraft:netherite_pickaxe": { icon: "textures/items/netherite_pickaxe", displayName: "Netherite Pickaxe" },
    "minecraft:diamond_helmet": { icon: "textures/items/diamond_helmet", displayName: "Diamond Helmet" },
    "minecraft:diamond_chestplate": { icon: "textures/items/diamond_chestplate", displayName: "Diamond Chestplate" },
    "minecraft:diamond_leggings": { icon: "textures/items/diamond_leggings", displayName: "Diamond Leggings" },
    "minecraft:diamond_boots": { icon: "textures/items/diamond_boots", displayName: "Diamond Boots" },
    "minecraft:netherite_helmet": { icon: "textures/items/netherite_helmet", displayName: "Netherite Helmet" },
    "minecraft:netherite_chestplate": { icon: "textures/items/netherite_chestplate", displayName: "Netherite Chestplate" },
    "minecraft:netherite_leggings": { icon: "textures/items/netherite_leggings", displayName: "Netherite Leggings" },
    "minecraft:netherite_boots": { icon: "textures/items/netherite_boots", displayName: "Netherite Boots" },
    "minecraft:oak_log": { icon: "textures/blocks/log_oak_top", displayName: "Oak Log" },
    "minecraft:spruce_log": { icon: "textures/blocks/log_spruce_top", displayName: "Spruce Log" },
    "minecraft:birch_log": { icon: "textures/blocks/log_birch_top", displayName: "Birch Log" },
    "minecraft:jungle_log": { icon: "textures/blocks/log_jungle_top", displayName: "Jungle Log" },
    "minecraft:acacia_log": { icon: "textures/blocks/log_acacia_top", displayName: "Acacia Log" },
    "minecraft:dark_oak_log": { icon: "textures/blocks/log_big_oak_top", displayName: "Dark Oak Log" },
    "minecraft:mangrove_log": { icon: "textures/blocks/mangrove_log_top", displayName: "Mangrove Log" },
    "minecraft:cherry_log": { icon: "textures/blocks/cherry_log_top", displayName: "Cherry Log" },
    "minecraft:crimson_stem": { icon: "textures/blocks/huge_fungus/crimson_log_top", displayName: "Crimson Stem" },
    "minecraft:warped_stem": { icon: "textures/blocks/huge_fungus/warped_stem_top", displayName: "Warped Stem" },
    "minecraft:stone": { icon: "textures/blocks/stone", displayName: "Stone" },
    "minecraft:cobblestone": { icon: "textures/blocks/cobblestone", displayName: "Cobblestone" },
    "minecraft:dirt": { icon: "textures/blocks/dirt", displayName: "Dirt" },
    "minecraft:sand": { icon: "textures/blocks/sand", displayName: "Sand" },
    "minecraft:gravel": { icon: "textures/blocks/gravel", displayName: "Gravel" },
    "minecraft:glass": { icon: "textures/blocks/glass", displayName: "Glass" },
    "minecraft:terracotta": { icon: "textures/blocks/hardened_clay", displayName: "Terracotta" },
    "minecraft:white_concrete": { icon: "textures/blocks/concrete_white", displayName: "White Concrete" },
    "minecraft:stone_bricks": { icon: "textures/blocks/stonebrick", displayName: "Stone Bricks" },
    "minecraft:obsidian": { icon: "textures/blocks/obsidian", displayName: "Obsidian" },
    "minecraft:glowstone": { icon: "textures/blocks/glowstone", displayName: "Glowstone" },
    "minecraft:netherrack": { icon: "textures/blocks/netherrack", displayName: "Netherrack" },
    "minecraft:end_stone": { icon: "textures/blocks/end_stone", displayName: "End Stone" },
    "minecraft:purpur_block": { icon: "textures/blocks/purpur_block", displayName: "Purpur Block" },
    "minecraft:cooked_beef": { icon: "textures/items/beef_cooked", displayName: "Steak" },
    "minecraft:cooked_porkchop": { icon: "textures/items/porkchop_cooked", displayName: "Cooked Porkchop" },
    "minecraft:bread": { icon: "textures/items/bread", displayName: "Bread" },
    "minecraft:golden_carrot": { icon: "textures/items/carrot_golden", displayName: "Golden Carrot" },
    "minecraft:cooked_salmon": { icon: "textures/items/fish_salmon_cooked", displayName: "Cooked Salmon" },
    "minecraft:cooked_cod": { icon: "textures/items/fish_cooked", displayName: "Cooked Cod" },
    "minecraft:chorus_fruit": { icon: "textures/items/chorus_fruit", displayName: "Chorus Fruit" },
    "minecraft:wheat": { icon: "textures/items/wheat", displayName: "Wheat" },
    "minecraft:carrot": { icon: "textures/items/carrot", displayName: "Carrot" },
    "minecraft:potato": { icon: "textures/items/potato", displayName: "Potato" },
    "minecraft:melon_slice": { icon: "textures/items/melon", displayName: "Melon Slice" },
    "minecraft:pumpkin": { icon: "textures/blocks/pumpkin_face_off", displayName: "Pumpkin" },
    "minecraft:sugar_cane": { icon: "textures/items/reeds", displayName: "Sugar Cane" },
    "minecraft:nether_wart": { icon: "textures/items/nether_wart", displayName: "Nether Wart" },
    "minecraft:enchanted_book": { icon: "textures/items/book_enchanted", displayName: "Enchanted Book" },
    "exe:panel": { icon: "textures/items/breeze_rod", displayName: "§l§bPanel§r" },
    "minecraft:allay_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_allay", displayName: "Allay Spawn Egg" },
    "minecraft:axolotl_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_axolotl", displayName: "Axolotl Spawn Egg" },
    "minecraft:bat_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_bat", displayName: "Bat Spawn Egg" },
    "minecraft:bee_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_bee", displayName: "Bee Spawn Egg" },
    "minecraft:blaze_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_blaze", displayName: "Blaze Spawn Egg" },
    "minecraft:bogged_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_bogged", displayName: "Bogged Spawn Egg" },
    "minecraft:breeze_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_breeze", displayName: "Breeze Spawn Egg" },
    "minecraft:camel_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_camel", displayName: "Camel Spawn Egg" },
    "minecraft:cat_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_cat", displayName: "Cat Spawn Egg" },
    "minecraft:cave_spider_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_cave_spider", displayName: "Cave Spider Spawn Egg" },
    "minecraft:chicken_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_chicken", displayName: "Chicken Spawn Egg" },
    "minecraft:cod_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_cod", displayName: "Cod Spawn Egg" },
    "minecraft:cow_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_cow", displayName: "Cow Spawn Egg" },
    "minecraft:creeper_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_creeper", displayName: "Creeper Spawn Egg" },
    "minecraft:dolphin_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_dolphin", displayName: "Dolphin Spawn Egg" },
    "minecraft:donkey_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_donkey", displayName: "Donkey Spawn Egg" },
    "minecraft:drowned_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_drowned", displayName: "Drowned Spawn Egg" },
    "minecraft:elder_guardian_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_elder_guardian", displayName: "Elder Guardian Spawn Egg" },
    "minecraft:ender_dragon_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_ender_dragon", displayName: "Ender Dragon Spawn Egg" },
    "minecraft:enderman_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_enderman", displayName: "Enderman Spawn Egg" },
    "minecraft:endermite_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_endermite", displayName: "Endermite Spawn Egg" },
    "minecraft:evoker_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_evoker", displayName: "Evoker Spawn Egg" },
    "minecraft:fox_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_fox", displayName: "Fox Spawn Egg" },
    "minecraft:frog_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_frog", displayName: "Frog Spawn Egg" },
    "minecraft:ghast_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_ghast", displayName: "Ghast Spawn Egg" },
    "minecraft:glow_squid_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_glow_squid", displayName: "Glow Squid Spawn Egg" },
    "minecraft:goat_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_goat", displayName: "Goat Spawn Egg" },
    "minecraft:guardian_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_guardian", displayName: "Guardian Spawn Egg" },
    "minecraft:hoglin_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_hoglin", displayName: "Hoglin Spawn Egg" },
    "minecraft:horse_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_horse", displayName: "Horse Spawn Egg" },
    "minecraft:husk_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_husk", displayName: "Husk Spawn Egg" },
    "minecraft:iron_golem_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_iron_golem", displayName: "Iron Golem Spawn Egg" },
    "minecraft:llama_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_llama", displayName: "Llama Spawn Egg" },
    "minecraft:magma_cube_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_magma_cube", displayName: "Magma Cube Spawn Egg" },
    "minecraft:mooshroom_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_mooshroom", displayName: "Mooshroom Spawn Egg" },
    "minecraft:mule_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_mule", displayName: "Mule Spawn Egg" },
    "minecraft:ocelot_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_ocelot", displayName: "Ocelot Spawn Egg" },
    "minecraft:panda_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_panda", displayName: "Panda Spawn Egg" },
    "minecraft:parrot_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_parrot", displayName: "Parrot Spawn Egg" },
    "minecraft:phantom_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_phantom", displayName: "Phantom Spawn Egg" },
    "minecraft:pig_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_pig", displayName: "Pig Spawn Egg" },
    "minecraft:piglin_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_piglin", displayName: "Piglin Spawn Egg" },
    "minecraft:piglin_brute_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_piglin_brute", displayName: "Piglin Brute Spawn Egg" },
    "minecraft:pillager_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_pillager", displayName: "Pillager Spawn Egg" },
    "minecraft:polar_bear_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_polar_bear", displayName: "Polar Bear Spawn Egg" },
    "minecraft:pufferfish_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_pufferfish", displayName: "Pufferfish Spawn Egg" },
    "minecraft:rabbit_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_rabbit", displayName: "Rabbit Spawn Egg" },
    "minecraft:ravager_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_ravager", displayName: "Ravager Spawn Egg" },
    "minecraft:salmon_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_salmon", displayName: "Salmon Spawn Egg" },
    "minecraft:sheep_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_sheep", displayName: "Sheep Spawn Egg" },
    "minecraft:shulker_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_shulker", displayName: "Shulker Spawn Egg" },
    "minecraft:silverfish_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_silverfish", displayName: "Silverfish Spawn Egg" },
    "minecraft:skeleton_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_skeleton", displayName: "Skeleton Spawn Egg" },
    "minecraft:skeleton_horse_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_skeleton_horse", displayName: "Skeleton Horse Spawn Egg" },
    "minecraft:slime_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_slime", displayName: "Slime Spawn Egg" },
    "minecraft:sniffer_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_sniffer", displayName: "Sniffer Spawn Egg" },
    "minecraft:snow_golem_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_snow_golem", displayName: "Snow Golem Spawn Egg" },
    "minecraft:spider_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_spider", displayName: "Spider Spawn Egg" },
    "minecraft:squid_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_squid", displayName: "Squid Spawn Egg" },
    "minecraft:stray_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_stray", displayName: "Stray Spawn Egg" },
    "minecraft:strider_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_strider", displayName: "Strider Spawn Egg" },
    "minecraft:tadpole_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_tadpole", displayName: "Tadpole Spawn Egg" },
    "minecraft:trader_llama_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_trader_llama", displayName: "Trader Llama Spawn Egg" },
    "minecraft:tropical_fish_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_tropicalfish", displayName: "Tropical Fish Spawn Egg" },
    "minecraft:turtle_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_turtle", displayName: "Turtle Spawn Egg" },
    "minecraft:vex_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_vex", displayName: "Vex Spawn Egg" },
    "minecraft:villager_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_villager", displayName: "Villager Spawn Egg" },
    "minecraft:vindicator_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_vindicator", displayName: "Vindicator Spawn Egg" },
    "minecraft:warden_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_warden", displayName: "Warden Spawn Egg" },
    "minecraft:witch_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_witch", displayName: "Witch Spawn Egg" },
    "minecraft:wither_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_wither", displayName: "Wither Spawn Egg" },
    "minecraft:wither_skeleton_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_wither_skeleton", displayName: "Wither Skeleton Spawn Egg" },
    "minecraft:wolf_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_wolf", displayName: "Wolf Spawn Egg" },
    "minecraft:zoglin_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_zoglin", displayName: "Zoglin Spawn Egg" },
    "minecraft:zombie_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_zombie", displayName: "Zombie Spawn Egg" },
    "minecraft:zombie_horse_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_zombie_horse", displayName: "Zombie Horse Spawn Egg" },
    "minecraft:zombified_piglin_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_zombified_piglin", displayName: "Zombified Piglin Spawn Egg" },
    "minecraft:zombie_villager_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_zombie_villager", displayName: "Zombie Villager Spawn Egg" },
    "minecraft:armadillo_spawn_egg": { icon: "textures/items/spawn_eggs/spawn_egg_armadillo", displayName: "Armadillo Spawn Egg" }
};