// Auto-generated by scripts/generate-command-index.js
/* eslint-disable */
import { commandManager, CustomCommand } from './commandManager.js';

import cmdAnnouncement from './announcement.js';
import cmdBalance from './balance.js';
import cmdBan from './ban.js';
import cmdBounty from './bounty.js';
import cmdChattoconsole from './chattoconsole.js';
import cmdClear from './clear.js';
import cmdClearchat from './clearchat.js';
import cmdDeathcoords from './deathcoords.js';
import cmdDimensionLock from './dimensionLock.js';
import cmdFloatingtext from './floatingtext.js';
import cmdFreeze from './freeze.js';
import cmdGamemode from './gamemode.js';
import cmdHelp from './help.js';
import cmdHome from './home.js';
import cmdInventory from './inventory.js';
import cmdKick from './kick.js';
import cmdKit from './kit.js';
import cmdLinks from './links.js';
import cmdLog from './log.js';
import cmdMute from './mute.js';
import cmdPanel from './panel.js';
import cmdPay from './pay.js';
import cmdPvp from './pvp.js';
import cmdRank from './rank.js';
import cmdReload from './reload.js';
import cmdReport from './report.js';
import cmdRestart from './restart.js';
import cmdRtp from './rtp.js';
import cmdRules from './rules.js';
import cmdSave from './save.js';
import cmdSetbalance from './setbalance.js';
import cmdShop from './shop.js';
import cmdSpawn from './spawn.js';
import cmdStatus from './status.js';
import cmdTeam from './team.js';
import cmdTest from './test.js';
import cmdTestCommand from './testCommand.js';
import cmdTp from './tp.js';
import cmdTpa from './tpa.js';
import cmdVanish from './vanish.js';
import cmdVersion from './version.js';
import cmdWarp from './warp.js';
import cmdXraynotify from './xraynotify.js';

export function loadCommands() {
    const commands = [
        cmdAnnouncement,
        cmdBalance,
        cmdBan,
        cmdBounty,
        cmdChattoconsole,
        cmdClear,
        cmdClearchat,
        cmdDeathcoords,
        cmdDimensionLock,
        cmdFloatingtext,
        cmdFreeze,
        cmdGamemode,
        cmdHelp,
        cmdHome,
        cmdInventory,
        cmdKick,
        cmdKit,
        cmdLinks,
        cmdLog,
        cmdMute,
        cmdPanel,
        cmdPay,
        cmdPvp,
        cmdRank,
        cmdReload,
        cmdReport,
        cmdRestart,
        cmdRtp,
        cmdRules,
        cmdSave,
        cmdSetbalance,
        cmdShop,
        cmdSpawn,
        cmdStatus,
        cmdTeam,
        cmdTest,
        cmdTestCommand,
        cmdTp,
        cmdTpa,
        cmdVanish,
        cmdVersion,
        cmdWarp,
        cmdXraynotify
    ];

    commands.forEach(cmdModule => {
        if (Array.isArray(cmdModule)) {
            cmdModule.forEach(cmd => commandManager.register(cmd as CustomCommand));
        } else if (cmdModule) {
            commandManager.register(cmdModule as CustomCommand);
        }
    });
}
