// Auto-generated by scripts/generate-command-index.js
import { commandManager, CustomCommand } from './commandManager.js';

import cmd_announcement from './announcement.js';
import cmd_balance from './balance.js';
import cmd_ban from './ban.js';
import cmd_bounty from './bounty.js';
import cmd_chattoconsole from './chattoconsole.js';
import cmd_clear from './clear.js';
import cmd_clearchat from './clearchat.js';
import cmd_deathcoords from './deathcoords.js';
import cmd_dimensionLock from './dimensionLock.js';
import cmd_floatingtext from './floatingtext.js';
import cmd_freeze from './freeze.js';
import cmd_gamemode from './gamemode.js';
import cmd_help from './help.js';
import cmd_home from './home.js';
import cmd_inventory from './inventory.js';
import cmd_kick from './kick.js';
import cmd_kit from './kit.js';
import cmd_links from './links.js';
import cmd_log from './log.js';
import cmd_mute from './mute.js';
import cmd_panel from './panel.js';
import cmd_pay from './pay.js';
import cmd_pvp from './pvp.js';
import cmd_rank from './rank.js';
import cmd_reload from './reload.js';
import cmd_report from './report.js';
import cmd_restart from './restart.js';
import cmd_rtp from './rtp.js';
import cmd_rules from './rules.js';
import cmd_save from './save.js';
import cmd_setbalance from './setbalance.js';
import cmd_shop from './shop.js';
import cmd_spawn from './spawn.js';
import cmd_status from './status.js';
import cmd_team from './team.js';
import cmd_test from './test.js';
import cmd_testCommand from './testCommand.js';
import cmd_tp from './tp.js';
import cmd_tpa from './tpa.js';
import cmd_vanish from './vanish.js';
import cmd_version from './version.js';
import cmd_warp from './warp.js';
import cmd_xraynotify from './xraynotify.js';

export function loadCommands() {
    const commands = [
        cmd_announcement,
        cmd_balance,
        cmd_ban,
        cmd_bounty,
        cmd_chattoconsole,
        cmd_clear,
        cmd_clearchat,
        cmd_deathcoords,
        cmd_dimensionLock,
        cmd_floatingtext,
        cmd_freeze,
        cmd_gamemode,
        cmd_help,
        cmd_home,
        cmd_inventory,
        cmd_kick,
        cmd_kit,
        cmd_links,
        cmd_log,
        cmd_mute,
        cmd_panel,
        cmd_pay,
        cmd_pvp,
        cmd_rank,
        cmd_reload,
        cmd_report,
        cmd_restart,
        cmd_rtp,
        cmd_rules,
        cmd_save,
        cmd_setbalance,
        cmd_shop,
        cmd_spawn,
        cmd_status,
        cmd_team,
        cmd_test,
        cmd_testCommand,
        cmd_tp,
        cmd_tpa,
        cmd_vanish,
        cmd_version,
        cmd_warp,
        cmd_xraynotify
    ];

    commands.forEach(cmdModule => {
        if (Array.isArray(cmdModule)) {
            cmdModule.forEach(cmd => commandManager.register(cmd as CustomCommand));
        } else if (cmdModule) {
            commandManager.register(cmdModule as CustomCommand);
        }
    });
}
