// Auto-generated by scripts/generate-command-index.js
import { commandManager } from './commandManager.js';

import cmdLegacyAnnouncement from './announcement.js';
import cmdLegacyBounty from './bounty.js';
import cmdLegacyChattoconsole from './chattoconsole.js';
import cmdLegacyClear from './clear.js';
import cmdLegacyClearchat from './clearchat.js';
import cmdLegacyDebug from './debug.js';
import cmdLegacyDimensionLock from './dimensionLock.js';
import cmdLegacyFloatingtext from './floatingtext.js';
import cmdLegacyGamemode from './gamemode.js';
import cmdLegacyHelp from './help.js';
import cmdLegacyInventory from './inventory.js';
import cmdLegacyKit from './kit.js';
import cmdLegacyLinks from './links.js';
import cmdLegacyLog from './log.js';
import cmdLegacyPanel from './panel.js';
import cmdLegacyPvp from './pvp.js';
import cmdLegacyRank from './rank.js';
import cmdLegacyReload from './reload.js';
import cmdLegacyRestart from './restart.js';
import cmdLegacyRules from './rules.js';
import cmdLegacySave from './save.js';
import cmdLegacySidebar from './sidebar.js';
import cmdLegacySpawn from './spawn.js';
import cmdLegacyStatus from './status.js';
import cmdLegacyVanish from './vanish.js';
import cmdLegacyVersion from './version.js';
import cmdLegacyXraynotify from './xraynotify.js';
import cmdAnticheatLogs from '@features/anticheat/commands/logs.js';
import cmdAnticheatNotify from '@features/anticheat/commands/notify.js';
import cmdEconomyBalance from '@features/economy/commands/balance.js';
import cmdEconomyPay from '@features/economy/commands/pay.js';
import cmdEconomySetbalance from '@features/economy/commands/setbalance.js';
import cmdModerationBan from '@features/moderation/commands/ban.js';
import cmdModerationFreeze from '@features/moderation/commands/freeze.js';
import cmdModerationKick from '@features/moderation/commands/kick.js';
import cmdModerationMute from '@features/moderation/commands/mute.js';
import cmdModerationReport from '@features/moderation/commands/report.js';
import cmdShopShop from '@features/shop/commands/shop.js';
import cmdTeamsTeam from '@features/teams/commands/team.js';
import cmdTeleportationDeathcoords from '@features/teleportation/commands/deathcoords.js';
import cmdTeleportationHome from '@features/teleportation/commands/home.js';
import cmdTeleportationRtp from '@features/teleportation/commands/rtp.js';
import cmdTeleportationTp from '@features/teleportation/commands/tp.js';
import cmdTeleportationTpa from '@features/teleportation/commands/tpa.js';
import cmdTeleportationWarp from '@features/teleportation/commands/warp.js';

export function loadCommands() {
    const commands = [
        cmdLegacyAnnouncement,
        cmdLegacyBounty,
        cmdLegacyChattoconsole,
        cmdLegacyClear,
        cmdLegacyClearchat,
        cmdLegacyDebug,
        cmdLegacyDimensionLock,
        cmdLegacyFloatingtext,
        cmdLegacyGamemode,
        cmdLegacyHelp,
        cmdLegacyInventory,
        cmdLegacyKit,
        cmdLegacyLinks,
        cmdLegacyLog,
        cmdLegacyPanel,
        cmdLegacyPvp,
        cmdLegacyRank,
        cmdLegacyReload,
        cmdLegacyRestart,
        cmdLegacyRules,
        cmdLegacySave,
        cmdLegacySidebar,
        cmdLegacySpawn,
        cmdLegacyStatus,
        cmdLegacyVanish,
        cmdLegacyVersion,
        cmdLegacyXraynotify,
        cmdAnticheatLogs,
        cmdAnticheatNotify,
        cmdEconomyBalance,
        cmdEconomyPay,
        cmdEconomySetbalance,
        cmdModerationBan,
        cmdModerationFreeze,
        cmdModerationKick,
        cmdModerationMute,
        cmdModerationReport,
        cmdShopShop,
        cmdTeamsTeam,
        cmdTeleportationDeathcoords,
        cmdTeleportationHome,
        cmdTeleportationRtp,
        cmdTeleportationTp,
        cmdTeleportationTpa,
        cmdTeleportationWarp
    ];

    commands.forEach(cmdModule => {
        if (Array.isArray(cmdModule)) {
            cmdModule.forEach(cmd => commandManager.register(cmd));
        } else if (cmdModule) {
            commandManager.register(cmdModule);
        }
    });
}
