import fs from 'fs';
import path from 'path';
import { globSync } from 'glob';
import chokidar from 'chokidar';

const isWatch = process.argv.includes('--watch');
const isMinify = process.argv.includes('--minify') || process.env.NODE_ENV === 'production';
const outDir = 'build/behavior/scripts';

// 1. Port the custom plugin
const generateCommandIndexPlugin = {
    name: 'generate-command-index',
    setup(build) {
        build.onLoad({ filter: /src[\\/]core[\\/]commands[\\/]index\.ts$/ }, async () => {
            console.log('Generating command index for Bun...');

            const SRC_DIR = path.resolve('src');
            const FEATURES_DIR = path.join(SRC_DIR, 'features');
            const EXCLUSIONS = new Set(['index.ts']);

            const featureDirs = [];
            try {
                const registryTsPath = path.resolve('src/core/featureRegistry.ts');
                const content = await fs.promises.readFile(registryTsPath, 'utf8');

                // Match lines like: { id: 'anticheat', load: ... }
                const regex = /\{\s*id:\s*'([^']+)'/g;
                let match;
                while ((match = regex.exec(content)) !== null) {
                    featureDirs.push(match[1]);
                }
            } catch (error) {
                console.warn(`Error reading src/core/featureRegistry.ts: ${error.message}`);
            }

            const commandList = [];

            if (featureDirs.length > 0) {
                await Promise.all(
                    featureDirs.map(async (feature) => {
                        const cmdDir = path.join(FEATURES_DIR, feature, 'commands');
                        try {
                            const entries = await fs.promises.readdir(cmdDir);
                            const files = entries.filter((file) => file.endsWith('.ts') && !EXCLUSIONS.has(file));

                            for (const file of files) {
                                const baseName = path.basename(file, '.ts');
                                const safeFeature = feature.replaceAll(/[^a-zA-Z0-9]/g, '');
                                const safeFile = baseName.replaceAll(/[^a-zA-Z0-9]/g, '');
                                const varName = `cmd${safeFeature.charAt(0).toUpperCase() + safeFeature.slice(1)}${safeFile.charAt(0).toUpperCase() + safeFile.slice(1)}`;
                                const importPath = `@features/${feature}/commands/${baseName}.js`;

                                commandList.push({
                                    varName,
                                    importPath
                                });
                            }
                        } catch {
                            // Directory might not exist or be unreadable
                        }
                    })
                );
            }

            commandList.sort((a, b) => a.varName.localeCompare(b.varName));

            console.log(`Found ${commandList.length} command files.`);

            const imports = commandList.map((cmd) => `import ${cmd.varName} from '${cmd.importPath}';`).join('\n');
            const list = commandList.map((cmd) => cmd.varName).join(',\n        ');

            const content = `// Auto-generated by Bun plugin
import { isDefined } from '@lib/guards.js';
import { commandManager } from './commandManager.js';

${imports}

export function loadCommands() {
    const commandModules = [
        ${list}
    ];

    for (const mod of commandModules) {
        if (isDefined(mod)) {
            if (Array.isArray(mod)) {
                for (const cmd of mod) commandManager.register(cmd);
            } else {
                commandManager.register(mod);
            }
        }
    }
}
`;

            return {
                contents: content,
                loader: 'ts'
            };
        });
    }
};

async function postBuild() {
    // We need to rename the generated `.default.js` files to `.js`
    // However, if the user has defined a custom configuration file (e.g. config.ts),
    // we should not overwrite it with the default one.
    const generatedFiles = globSync('**/*.default.js', { cwd: outDir });

    for (const file of generatedFiles) {
        const oldPath = path.join(outDir, file);
        const newPath = oldPath.replace('.default.js', '.js');

        if (fs.existsSync(newPath)) {
            // A custom config was compiled. Delete the default one instead of overwriting.
            fs.rmSync(oldPath);
            if (fs.existsSync(oldPath + '.map')) {
                fs.rmSync(oldPath + '.map');
            }
        } else {
            // Rename default to standard
            fs.renameSync(oldPath, newPath);

            // Also rename maps if they exist
            if (fs.existsSync(oldPath + '.map')) {
                fs.renameSync(oldPath + '.map', newPath + '.map');
            }
        }
    }
}

async function runBuild() {
    console.log('Building scripts with Bun...');

    const configFiles = globSync('src/**/*Config{.ts,.default.ts}', {
        ignore: [
            '**/__tests__/**',
            '**/__mocks__/**',
            'src/core/configManager*.ts',
            'src/core/configurations.ts',
            'src/core/configLoader.ts',
            'src/features/anticheat/anticheatConfigLoader.ts'
        ]
    });

    configFiles.push('src/config.default.ts');

    const entrypoints = ['src/main.ts', ...configFiles];

    const external = [
        '@minecraft/server',
        '@minecraft/server-ui',
        '@minecraft/server-gametest',
        '@minecraft/debug-utilities',
        '@minecraft/common',
        ...configFiles.map((file) => {
            let relativePath = file.replace('src/', './').replace('.ts', '.js');
            if (relativePath.endsWith('.default.js')) {
                relativePath = relativePath.replace('.default.js', '.js');
            }
            return relativePath;
        })
    ];

    try {
        const result = await Bun.build({
            entrypoints,
            outdir: outDir,
            target: 'browser',
            format: 'esm',
            sourcemap: 'external',
            minify: isMinify,
            external,
            plugins: [generateCommandIndexPlugin]
        });

        if (!result.success) {
            console.error('Build failed:');
            for (const message of result.logs) {
                console.error(message);
            }
        } else {
            await postBuild();
            console.log('Scripts build complete!');
        }
    } catch (err) {
        console.error('An error occurred during build:', err);
    }
}

// Run initial build
runBuild();

if (isWatch) {
    console.log('Watching for script changes...');
    const watcher = chokidar.watch('src', {
        ignoreInitial: true,
        ignored: [/(^|[/\\])\../]
    });

    // Debounce rebuilds
    let timeout;
    const triggerBuild = () => {
        clearTimeout(timeout);
        timeout = setTimeout(() => runBuild(), 300);
    };

    watcher.on('add', triggerBuild);
    watcher.on('change', triggerBuild);
    watcher.on('unlink', triggerBuild);
}
